name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo add-apt-repository universe && sudo apt-get update
    - name: update-premake
      run: sudo add-apt-repository ppa:beauman/marley && sudo apt-get update

    - name: getdeps
      run: sudo apt install build-essential libx11-dev premake5
            
    - name: premake
      run: premake5 gmake2
    
    - name: compile-debug
      run: export MAKEFLAGS=-j8 && make verbose=1 config=debug
    - name: compile-release
      run: export MAKEFLAGS=-j8 && make verbose=1 config=release
    
      
      
      
